text = input("Enter a message: ")
print("Lowercase: ", text.lower())
print("Uppercase: ", text.upper())
print("Capitalized: ", text.capitalize())
print("Title case: ", text.title())
words = text.split()
print(words)
print("Alphabetic first word: ", sorted(words))
print("Alphabetic last word: ", sorted(words, reverse=True))